### ISSUE TITLE
Numerous build errors on Mac and Linux - extension is expected to be unavailable to the users

### ISSUE THREAD

**Issue by fedorov** [SBU-BMI/SlicerPathology#49]
![image](https://cloud.githubusercontent.com/assets/313942/16741847/1e1cf87a-4773-11e6-9c20-1025a82b99e2.png)

**Comment by fedorov** [comment]
http://slicer.cdash.org/index.php?project=Slicer4&display=project

**Comment by fedorov** [comment]
@naucoin can help @ebremer look into this?

**Comment by naucoin** [comment]
Looking into it now, suspecting VTKv7 migration issues.

**Comment by fedorov** [comment]
errors for linux: http://slicer.cdash.org/viewBuildError.php?buildid=864970

Slicer r25242

**Comment by ebremer** [comment]
Compiled on Ubuntu 16.x as of today

**Comment by ebremer** [comment]
trunk@25237

**Comment by ebremer** [comment]
Compiles and runs fine on an clean Ubuntu 14.x machine

**Comment by naucoin** [comment]
Determined so far on sentinelle:
- SlicerPathology builds stand alone succesfully
- SlicerPathology fails to build when done via the ExtensionsIndex method because that build process is over riding the CMakeLists.txt command to not wrap certain files when doing the python wrapping. 

There is a change in VTK7 to allow using WRAP_EXCLUDE_PYTHON not just a general WRAP_EXCLUDE command, but that gets ignored as well:
http://www.vtk.org/Wiki/VTK/Python_Wrapping_FAQ
@msmolens committed a change to SlicerPathology to fix this on Jul 11:
https://github.com/SBU-BMI/SlicerPathology/commit/c82a227e2b4c41799ed58c5df3bb93951ceab561
but the SlicerPathology.s4ext currently in the extension index is pointing to a hash from Jun 21, not master:
https://github.com/Slicer/ExtensionsIndex/commit/e6bb2ad76f843697ac826485e4fe49374b326382

This pull request should fix building on the factory on Linux and Mac:
https://github.com/Slicer/ExtensionsIndex/pull/1347

**Comment by fedorov** [comment]
Sounds promising, thanks for investigating this!

I see, I reset it from master. We should change it to point to master.

**Comment by fedorov** [comment]
resolved, @naucoin will add details

**Comment by naucoin** [comment]
The pull request above fixed building SlicerPathology, and this change to Slicer fixed the failing tests on Windows for SlicerOpenCV:
https://github.com/Slicer/Slicer/commit/96c1d59ed0b2847e3c526be8063ca786429a92bf
so now SlicerPathology is building on the factory on windows.

**Comment by tdiprima** [comment]
I resolved the Linux/Mac/Windows compiler issues some time at the end of April 2017.
Additionally, the Mac and Windows compile errors were fixed in #81.
