### ISSUE TITLE
Unreachable code: ShortCutEffect.py

### ISSUE THREAD

**Issue by tdiprima** [SBU-BMI/SlicerPathology#63]
Function **[runQTCGA_Template()](https://github.com/SBU-BMI/SlicerPathology/blob/master/ShortCutEffect/ShortCutEffect.py#L547-L548)** is defined, and then returns straight away.  So the rest of the [code](https://github.com/SBU-BMI/SlicerPathology/blob/master/ShortCutEffect/ShortCutEffect.py#L549-L571) in this function is never called.

Same thing with **[runQTCGA_Refine_Curvature()](https://github.com/SBU-BMI/SlicerPathology/blob/master/ShortCutEffect/ShortCutEffect.py#L606-L607)**.

@ebremer,  @gaoyi  &mdash; Are these two methods purposely not being called?  Can we write a comment indicating such, or can we delete the return statements there?

**Comment by fedorov** [comment]
@tdiprima no one at our side was directly involved in writing that code. The question is to @ebremer and @gaoyi.

**Comment by tdiprima** [comment]
@fedorov OK thanks.  I was looking at the "contributors" on that code.  That's why I asked.  Sorry to bother you.

**Comment by fedorov** [comment]
Tammy, you don't bother me - I just wanted to clarify.

It is difficult to trace the history of this code, since it was not originally developed in git/github, so even "Blame" feature (you found it, right?) does not help here.

![image](https://cloud.githubusercontent.com/assets/313942/23809583/340aba90-059c-11e7-8fa8-53cb6294e125.png)

**Comment by tdiprima** [comment]
Yes, exactly :)
